### ISSUE TITLE
(Crash Report)incompatible  With CMDCam v1.1.4 mc1.11.2 (Unable to launch java.lang.reflect.Invocation)

### ISSUE THREAD

**Issue by Lightone** [CreativeMD/ItemPhysic#33]
the game crash instanlty you start the game, if you remove the CMDCam mod all work fine,

tested with the recommended forge and lasted Items Physic
 

[Paste bin ](https://pastebin.com/XMqj2fAq)
Only generate the last log 
<details>
  <summary>Click to expand</summary>
`[21:15:15] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:15:15] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:15:15] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:15:15] [main/INFO]: Forge Mod Loader version 13.20.0.2228 for Minecraft 1.11.2 loading
[21:15:15] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_121, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_121
[21:15:15] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.2.jar
[21:15:15] [main/WARN]: The coremod com.creativemd.cmdcam.transform.CamPatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:15:15] [main/WARN]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:15:15] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:15:15] [main/WARN]: The coremod com.creativemd.itemphysic.ItemPatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:15:15] [main/WARN]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:15:15] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.11.2_HD_U_B7.jar
[21:15:15] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:15:15] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[21:15:15] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[21:15:15] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:15:15] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:15:15] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:15:15] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[21:15:15] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[21:15:15] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[21:15:15] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
[21:15:15] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/C:/Users/CarlosAlberto/AppData/Roaming/.minecraft/mods/OptiFine_1.11.2_HD_U_B7.jar
[21:15:15] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\mods\OptiFine_1.11.2_HD_U_B7.jar
[21:15:15] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:15:19] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[21:15:19] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[21:15:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:15:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:15:20] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:15:20] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:15:20] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:15:20] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:15:20] [main/INFO]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[21:15:20] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:15:21] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:15:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:15:21] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[21:15:21] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:15:21] [main/INFO]: Patching net.minecraft.client.Minecraft... (bes)
[21:15:22] [main/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:52]: [cmdcam] Patched net.minecraft.client.entity.EntityPlayerSP ...
[21:15:22] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.creativemd.itemphysic.ItemTransformer@2787de58 from coremod ItemPatchingLoader
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:257) ~[forge-1.11.2-13.20.0.2228.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NullPointerException
	at com.creativemd.itemphysic.ItemTransformer$4.transform(ItemTransformer.java:268) ~[ItemTransformer$4.class:?]
	at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:46) ~[CreativeTransformer.class:?]
	at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:33) ~[CreativeTransformer.class:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253) ~[forge-1.11.2-13.20.0.2228.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`
</details>

**Comment by CreativeMD** [comment]
I tested it and everything works just fine (CreativeCore v1.7.1, ItemPhysic v1.4.2 and CMDCam 1.1.4). To be honest i have no idea why this is happening. Maybe try to update to newer forge versions? If not try to remove all of the other mods as well and see if it is still happening.

**Comment by Lightone** [comment]
Forge forge-1.11.2-13.20.0.2282 (last)
jre1.8.0_121 64 bits

Mods 

CMDCam v1.1.4 mc1.11.2
ItemPhysic Full 1.4.2 mc1.11.2
CreativeCore v1.7.0 mc1.11.2

Same crash [Pastebin](https://pastebin.com/JbiGgMsh)

<details>
  <summary>Click to expand crash log</summary>
`[13:41:27] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
[13:41:27] [main/INFO] [FML/]: Forge Mod Loader version 13.20.0.2282 for Minecraft 1.11.2 loading
[13:41:27] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_121, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_121
[13:41:27] [main/DEBUG] [FML/]: Java classpath at launch is C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.11.2-13.20.0.2282\forge-1.11.2-13.20.0.2282.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\jline\jline\2.13\jline-2.13.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\mojang\netty\1.6\netty-1.6.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.24\authlib-1.5.24.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.10.16\realms-1.10.16.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.0.12_mojang\fastutil-7.0.12_mojang.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;C:\Users\CarlosAlberto\AppData\Roaming\.minecraft\versions\1.11.2\1.11.2.jar
[13:41:27] [main/DEBUG] [FML/]: Java library path at launch is C:\Users\CARLOS~1\AppData\Local\Temp\23e6-c2ba-fd36-34ce
[13:41:27] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[13:41:27] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[13:41:27] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[13:41:27] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[13:41:27] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[13:41:27] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[13:41:27] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[13:41:27] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to C:\Users\CarlosAlberto\AppData\Roaming\.minecraft
[13:41:27] [main/DEBUG] [FML/]: Discovering coremods
[13:41:27] [main/DEBUG] [FML/]: Examining for coremod candidacy CMDCam v1.1.4 mc1.11.2.jar
[13:41:27] [main/TRACE] [FML/]: Adding CMDCam v1.1.4 mc1.11.2.jar to the list of known coremods, it will not be examined again
[13:41:27] [main/DEBUG] [FML/]: Instantiating coremod class CamPatchingLoader
[13:41:27] [main/WARN] [FML/]: The coremod com.creativemd.cmdcam.transform.CamPatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:41:27] [main/DEBUG] [FML/]: Enqueued coremod CamPatchingLoader
[13:41:27] [main/DEBUG] [FML/]: Examining for coremod candidacy CreativeCore v1.7.0 mc1.11.2.jar
[13:41:27] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in CreativeCore v1.7.0 mc1.11.2.jar, it will be examined later for regular @Mod instances
[13:41:27] [main/DEBUG] [FML/]: Instantiating coremod class CreativePatchingLoader
[13:41:27] [main/WARN] [FML/]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:41:27] [main/DEBUG] [FML/]: Enqueued coremod CreativePatchingLoader
[13:41:27] [main/DEBUG] [FML/]: Examining for coremod candidacy ItemPhysic Full 1.4.2 mc1.11.2.jar
[13:41:27] [main/TRACE] [FML/]: Adding ItemPhysic Full 1.4.2 mc1.11.2.jar to the list of known coremods, it will not be examined again
[13:41:27] [main/DEBUG] [FML/]: Instantiating coremod class ItemPatchingLoader
[13:41:27] [main/WARN] [FML/]: The coremod com.creativemd.itemphysic.ItemPatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:41:27] [main/DEBUG] [FML/]: Enqueued coremod ItemPatchingLoader
[13:41:27] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:41:27] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:41:27] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:41:27] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:41:27] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:27] [main/DEBUG] [FML/]: Injecting coremod FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin} class transformers
[13:41:27] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[13:41:27] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[13:41:27] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[13:41:27] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[13:41:27] [main/DEBUG] [FML/]: Injection complete
[13:41:27] [main/DEBUG] [FML/]: Running coremod plugin for FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin}
[13:41:27] [main/DEBUG] [FML/]: Running coremod plugin FMLCorePlugin
[13:41:29] [main/DEBUG] [FML/]: Read 971 binary patches
[13:41:29] [main/DEBUG] [FML/]: Loading deobfuscation resource /deobfuscation_data-1.11.2.lzma with 33539 records
[13:41:31] [main/INFO] [FML/]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[13:41:31] [main/INFO] [FML/]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[13:41:31] [main/DEBUG] [FML/]: Coremod plugin class FMLCorePlugin run successfully
[13:41:31] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:31] [main/DEBUG] [FML/]: Injecting coremod FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin} class transformers
[13:41:31] [main/DEBUG] [FML/]: Injection complete
[13:41:31] [main/DEBUG] [FML/]: Running coremod plugin for FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin}
[13:41:31] [main/DEBUG] [FML/]: Running coremod plugin FMLForgePlugin
[13:41:31] [main/DEBUG] [FML/]: Coremod plugin class FMLForgePlugin run successfully
[13:41:31] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:31] [main/DEBUG] [FML/]: Injecting coremod CamPatchingLoader {com.creativemd.cmdcam.transform.CamPatchingLoader} class transformers
[13:41:31] [main/TRACE] [FML/]: Registering transformer com.creativemd.cmdcam.transform.CamTransformer
[13:41:32] [main/DEBUG] [FML/]: Injection complete
[13:41:32] [main/DEBUG] [FML/]: Running coremod plugin for CamPatchingLoader {com.creativemd.cmdcam.transform.CamPatchingLoader}
[13:41:32] [main/DEBUG] [FML/]: Running coremod plugin CamPatchingLoader
[13:41:32] [main/DEBUG] [FML/]: Coremod plugin class CamPatchingLoader run successfully
[13:41:32] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:32] [main/DEBUG] [FML/]: Injecting coremod CreativePatchingLoader {com.creativemd.creativecore.core.CreativePatchingLoader} class transformers
[13:41:32] [main/DEBUG] [FML/]: Injection complete
[13:41:32] [main/DEBUG] [FML/]: Running coremod plugin for CreativePatchingLoader {com.creativemd.creativecore.core.CreativePatchingLoader}
[13:41:32] [main/DEBUG] [FML/]: Running coremod plugin CreativePatchingLoader
[13:41:32] [main/DEBUG] [FML/]: Coremod plugin class CreativePatchingLoader run successfully
[13:41:32] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:32] [main/DEBUG] [FML/]: Injecting coremod ItemPatchingLoader {com.creativemd.itemphysic.ItemPatchingLoader} class transformers
[13:41:32] [main/TRACE] [FML/]: Registering transformer com.creativemd.itemphysic.ItemTransformer
[13:41:32] [main/DEBUG] [FML/]: Injection complete
[13:41:32] [main/DEBUG] [FML/]: Running coremod plugin for ItemPatchingLoader {com.creativemd.itemphysic.ItemPatchingLoader}
[13:41:32] [main/DEBUG] [FML/]: Running coremod plugin ItemPatchingLoader
[13:41:32] [main/DEBUG] [FML/]: Coremod plugin class ItemPatchingLoader run successfully
[13:41:32] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:41:32] [main/DEBUG] [FML/]: Loaded 195 rules from AccessTransformer config file forge_at.cfg
[13:41:32] [main/DEBUG] [FML/]: Validating minecraft
[13:41:33] [main/DEBUG] [FML/]: Minecraft validated, launching...
[13:41:33] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:41:33] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:41:33] [main/INFO] [LaunchWrapper/]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[13:41:33] [main/INFO] [STDOUT/]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:52]: [cmdcam] Patched net.minecraft.client.entity.EntityPlayerSP ...
[13:41:34] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.creativemd.itemphysic.ItemTransformer@7e8a46b7 from coremod ItemPatchingLoader
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:257) ~[forge-1.11.2-13.20.0.2282.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NullPointerException
	at com.creativemd.itemphysic.ItemTransformer$4.transform(ItemTransformer.java:268) ~[ItemTransformer$4.class:?]
	at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:46) ~[CreativeTransformer.class:?]
	at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:33) ~[CreativeTransformer.class:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253) ~[forge-1.11.2-13.20.0.2282.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
	... 6 more
[13:41:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[13:41:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[13:41:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[13:41:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[13:41:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[13:41:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[13:41:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`
</details>

**Comment by CreativeMD** [comment]
Could you try out this version?
https://www.dropbox.com/s/yuv22quf7g9qzq5/CreativeCore%20v1.7.1%20mc1.11.2.jar?dl=1

**Comment by Lightone** [comment]
same crash with the new core.

Maybe only have bad luck xD, is not big deal i change the mod when i need use the camera xD

[crash log report ](https://pastebin.com/nsgBqAfA)

**Comment by CreativeMD** [comment]
This should fix it:
https://www.dropbox.com/s/5pp5zne3xmuhg6e/CMDCam%20v1.1.5%20mc1.11.2.jar?dl=1

**Comment by Lightone** [comment]
Fixed (i Hope you dont broken something when you try fix that xD)

test with the old core and new one and work fine.

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. I'm glad everything works fine now.

**Comment by Jaspermcvn** [comment]
I crashed the game immediately after installing the cmdcam mod and running minecraft, but before I could still get into the game without any problems.-.-
